### ISSUE TITLE
This feed keeps rolling

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#11]
This feed keeps rolling and rolling with no stoping:

.rssadd #globalnews Smithsonian http://feeds.feedburner.com/smithsonianmag/science-nature?format=xml

**Comment by RebelCodeBase** [comment]
This is because the feed has more than 100 items. You need to increase [MAX_HASHES_PER_FEED](https://github.com/f4bio/sopel-rss/blob/master/rss.py#L13).
