### ISSUE TITLE
rsslist

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#12]
When I do .rsslist this is all that is shown:

<rinzes> .rsslist
<gnews> #globalnews RTR http://feeds.reuters.com/reuters/topNews

Here is [rss]

[rss]
feeds = #globalnews RTR http://feeds.reuters.com/reuters/topNews,#globalnews FrontPageMag http://www.frontpagemag.com/point/rss.xml,#globalnews HuffingtonPost http://www.huffingtonpost.com/feeds/index.xml,#globalnews APSports http://hosted.ap.org/lineups/SPORTSHEADS.rss?SITE=AP&SECTION=HOME,#globalnews RealNews http://therealnews.com/rss/therealnews.rss,#globalnews SCOTUSblog http://www.scotusblog.com/feed/,#globalnews APEntertainment http://hosted.ap.org/lineups/ENTERTAINMENT.rss?SITE=AP&SECTION=HOME,#globalnews Netsec https://www.reddit.com/r/netsec/.rss,#globalnews USAToday http://rssfeeds.usatoday.com/usatoday-NewsTopStories,#globalnews CBS http://www.cbsnews.com/latest/rss/us,#globalnews WashTimes http://www.washingtontimes.com/rss/headlines/news/,#globalnews CC https://blog.creativecommons.org/feed/,#globalnews Al_Jazeera http://www.aljazeera.com/xml/rss/all.xml,#globalnews YahooNews https://news.yahoo.com/rss/topstories,#globalnews Economist http://www.economist.com/sections/united-states/rss.xml,#globalnews NewStatesman http://www.newstatesman.com/feeds_allsite/site_feed.php,#globalnews AP http://hosted.ap.org/lineups/TOPHEADS.rss?SITE=AP&SECTION=HOME,#globalnews Politico http://www.politico.com/rss/polls.xml,#globalnews APStrange http://hosted.ap.org/lineups/STRANGEHEADS.rss?SITE=AP&SECTION=HOME,#globalnews APUSnews http://hosted.ap.org/lineups/USHEADS.rss?SITE=AP&SECTION=HOME,#globalnews GlobeMail http://feeds.feedburner.com/TheGlobeAndMail-National,#globalnews APWorld http://hosted.ap.org/lineups/WORLDHEADS.rss?SITE=AP&SECTION=HOME,#globalnews Blacklisted http://feeds.feedburner.com/blacklistednews/hKxa,#globalnews NBC http://feeds.nbcnews.com/feeds/topstories,#globalnews GatewayPundit http://www.thegatewaypundit.com/feed/,#globalnews APScience http://hosted.ap.org/lineups/SCIENCEHEADS.rss?SITE=AP&SECTION=HOME,#globalnews REDDIT https://www.reddit.com/r/politics/.rss,#globalnews AboveTopSecret http://feeds.abovetopsecret.com/1.xml,#globalnews ABC http://feeds.abcnews.com/abcnews/usheadlines,#globalnews BBC http://feeds.bbci.co.uk/news/rss.xml,#globalnews APHealth http://hosted.ap.org/lineups/HEALTHHEADS.rss?SITE=AP&SECTION=HOME,#globalnews NY_Times http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml,#globalnews APBusiness http://hosted.ap.org/lineups/BUSINESSHEADS.rss?SITE=AP&SECTION=HOME,#globalnews Wikinews https://en.wikinews.org/w/index.php?title=Special:NewsFeed&feed=atom&categories=Published&notcategories=No%20publish|Archived|AutoArchived|disputed&namespace=0&count=30&hourcount=124&ordermethod=categoryadd&stablepages=only,#globalnews infowars http://www.infowars.com/feed,#globalnews CNN http://rss.cnn.com/rss/cnn_topstories.rss,#globalnews DailyKos http://feeds.dailykos.com/dailykos/index.xml,#globalnews WashPost http://feeds.washingtonpost.com/rss/national,#globalnews APTechnology http://hosted.ap.org/lineups/TECHHEADS.rss?SITE=AP&SECTION=HOME,#globalnews ARRL http://www.arrl.org/news/rss,#globalnews MediaMatters http://feeds.mediamatters.org/MediaMattersForAmerica-All,#globalnews RTRWorld http://feeds.reuters.com/Reuters/worldNews,#globalnews ESPN http://www.espn.com/espn/rss/news

**Comment by RebelCodeBase** [comment]
Are you using the latest version of the module? It is under heavy development at the moment.

**Comment by RebelCodeBase** [comment]
I recommend that you use `git clone https://github.com/f4bio/sopel-rss.git`and then symlink the module in your _.sopel/modules_ directory. This way, you can easily make a git pull regularly to pull in the latest version.

**Comment by rinzes** [comment]
I am using one that I got 3 hours ago. I used the git clone https://github.com/f4bio/sopel-rss.git. how do I go about doing a pull

**Comment by RebelCodeBase** [comment]
You are absolutely right: I've made a stupid mistake and did not catch that case correctly with a test. I've fixed both, please try again. (You make a pull simply with `git pull`. But you might have to `git commit -am 'Increased MAX_HASHES_PER_FEED'` first as you probably have local changes.)
