### ISSUE TITLE
rss feed problem

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#15]
I am getting lots of repeats on this site ==> https://news.yahoo.com/rss/topstories

I think it might be because of the rss feed structure. Your thoughts

**Comment by RebelCodeBase** [comment]
Please wait until I've implemented the FeedFormatter class. At the moment, the module takes for granted that the fields title, link and description exist and it uses all of thoses to hash an entry (which determines which entries are considered "new"). This works all right for my feeds but not for arbitrary feeds so I have to implement this in a much more general way.
