### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#16]
I was adding this feed and got the following:

 .rssadd #globalnews Discovery http://feeds.feedburner.com/DiscoveryNews-Top-Stories
<gnews> [ Science. World. Exploration. Seek for yourself. ] - feeds.feedburner.com
<gnews> IndexError: list index out of range (file "/home/znc/.sopel/modules/rss3.py", line 324, in __feedCheck)

here is the traceback

Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/module.py", line 343, in guarded
    return function(bot, trigger, _args, *_kwargs)
  File "/home/znc/.sopel/modules/rss3.py", line 44, in rssadd
    __rssadd(bot, channel, feedname, url)
  File "/home/znc/.sopel/modules/rss3.py", line 390, in __rssadd
    checkresults = __feedCheck(bot, feedreader, channel, feedname)
  File "/home/znc/.sopel/modules/rss3.py", line 324, in __feedCheck
    item = feed['entries'][0]
IndexError: list index out of range

**Comment by RebelCodeBase** [comment]
Listen, it's really nice that you are already using this module and that you are willing to do bug reports. But I have not yet released a stable version and I am in the middle of a major refactoring. Could you please wait a week or two until this refactoring is over? Just to give you an impression: the amount of code has nearly doubled over the last weekend and I am not yet done.

**Comment by rinzes** [comment]
OK.. was just trying to help

**Comment by RebelCodeBase** [comment]
I know that and I really appreciate it! It's just not the right moment to file bug reports while a major refactoring is going on. I hope that the module is feature-complete in a week or two. Then I'll release a version 0.1 and continue the development in a branch. From then on I'll be happy to receive bug reports and feature requests against that version.
