### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by Hippyjake** [f4bio/sopel-rss#2]
Hey thanks for the rss mod! but im getting this error when  configuring modules

``` python
Error loading rss: Non-ASCII character '\xe2' in file /home/pi/.sopel/modules/rss.py on line 383, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (rss.py, line 383) (../loader.py:195)
```

Thanks!

**Comment by RebelCodeBase** [comment]
Hey, I've written the new rss module and I hope I've fixed the unicode bug:
https://github.com/RebelCodeBase/sopel-rss

I've also opened a pull request here:
https://github.com/f4bio/sopel-rss/pull/3

Please tell me if you have further issues. I've seen your bug report here only by chance.
