### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by thenightfighter** [f4bio/sopel-rss#4]
Hey,
tried the plugin on a debian 7 host.

But got the following issue:
Error loading rss: Non-ASCII character '\xe2' in file /home/willie/.sopel/modules/rss.py on line 245, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (rss.py, line 245) (loader.py:195)

**Comment by RebelCodeBase** [comment]
This is strange as it is the same problem already reported in issues #2. It should be fixed by
`from __future__ import unicode_literals`
Could you please have a look if this line is present in your rss.py?

**Comment by thenightfighter** [comment]
Yep it's in the first line...

Also I got a strange error Error loading rss: No module named request (../../../../../../home/willie/.sopel/modules/rss.py:4) maybe it's known?

**Comment by RebelCodeBase** [comment]
The first error puzzles me and I doubt I can help you without having more information about your setup (os, language, python version, etc.)
As for the second error: it seems that you have not installed the python `request` module on your system. The installation method depends on how you manage your python modules (pip, apt-get, brew, etc.).

**Comment by rinzes** [comment]
you have to add the following at the top:

`# coding=utf8`

**Comment by rinzes** [comment]
I am unable to load this module as it fails with the RingBuffer

**Comment by RebelCodeBase** [comment]
Oh right, thanks a lot! This is defined in [PEP 263](https://www.python.org/dev/peps/pep-0263/) and I've added a line to the top of rss.py.
