### ISSUE TITLE
module fails to load

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#5]
I am unable to load this module as it fails with the RingBuffer... I am using python 2.7 on Ubuntu 14.04

**Comment by RebelCodeBase** [comment]
Could you please post the backtrace / error message?

**Comment by rinzes** [comment]
Welcome to Sopel. Loading modules...
Error loading rss: invalid syntax (rss.py, line 442) (loader.py:195)
Registered 43 modules,
1 modules failed to load

**Comment by rinzes** [comment]
https://code.activestate.com/recipes/68429-ring-buffer/

**Comment by rinzes** [comment]
I did a raw copy/paste of the rss.py to my ../.sopel/modules and now getting the following:

Error loading rss: No module named request (../../../../../../home/znc/.sopel/modules/rss.py:5)

Any Ideas?

**Comment by RebelCodeBase** [comment]
Your system is probably lacking the python library [urllib3](https://github.com/shazow/urllib3) from which urlopen is imported in [line 5](https://github.com/f4bio/sopel-rss/blob/master/rss.py#L5) of rss.py. You should install it through your preferred package manager.

**Comment by rinzes** [comment]
Requirement already satisfied (use --upgrade to upgrade): urllib3 in /usr/lib/python2.7/dist-packages

**Comment by RebelCodeBase** [comment]
What operating system is the bot installed on?

**Comment by rinzes** [comment]
Debian 8.3.0 Server 32-Bit

**Comment by RebelCodeBase** [comment]
Maybe you want to try out the [ansible role](/RebelCodeBase/ansible-role-sopel-runit-debianl) made for this module? It should not interfere with your current setup as is installs a local user sopel, checks out the source from github and uses runit to controll the sopel process.

**Comment by rinzes** [comment]
I get page not found... 404

I think it has something to do with me using Python 2.7 because I changed line 5 to:
from urllib2 import urlopen 
and it loaded without a error. cept the module did not work :)

**Comment by RebelCodeBase** [comment]
I think this is a python 2 vs. 3 issue. It turned out that we don't need that import line at all so I removed it.

**Comment by rinzes** [comment]
Thanks that fixed this issue but now I have others which I will address in New Issues

**Comment by RebelCodeBase** [comment]
Please go ahead ;-)
